### ISSUE TITLE
Error while converting duplicate leaf nodes

### ISSUE THREAD

**Issue by mallikarjunbpatil** [rsoldatenko/XMLConverter#1]
Hi,
When there are duplicated leaf nodes e.g (x,y) in the attached Image of  sample XML. JSON doesn't have an array ,It contains only one key value pair 
But it works , if the duplicated node is not a leaf node.

Please let me know , how i can fix this,
 Thanks in advance
Mallikarjun

![screen shot 2014-07-11 at 8 43 51 pm](https://cloud.githubusercontent.com/assets/2705053/3554524/7c3472e0-090d-11e4-8fc2-3930d205ec38.png)

**Comment by steffex** [comment]
I'm running into the same issue.

**Comment by rsoldatenko** [comment]
Fixed.
